# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvOBb7r0aXd0PM1SEqrLrmlPyn0Mi4AN
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

app = FastAPI()

model = joblib.load("phri_model.pkl")

class WeatherInput(BaseModel):
    temperature_c: float
    humidity_pct: float
    pm10_ug_m3: float
    wind_speed_kmh: float

def get_risk_level(phri: float) -> str:
    if phri < 30:
        return "LOW"
    elif phri < 60:
        return "MODERATE"
    elif phri < 80:
        return "HIGH"
    else:
        return "CRITICAL"

@app.post("/predict_risk")
def predict_risk(data: WeatherInput):
    features = np.array([[
        data.temperature_c,
        data.humidity_pct,
        data.pm10_ug_m3,
        data.wind_speed_kmh
    ]])

    prediction = model.predict(features)[0]
    phri = round(float(prediction[0]), 1)
    surge = round(float(prediction[1]), 1)

    return {
        "phri_score": phri,
        "risk_level": get_risk_level(phri),
        "projected_er_surge_pct": surge
    }