# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlBuhyytPcQILqs2LRxbdXf2A09E9FTW
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

df = pd.read_csv("weather_phri_dataset.csv")

# Defining weather elements as features (X) and target variables as targets (y)
X = df[['temperature_c', 'humidity_pct', 'pm10_ug_m3', 'wind_speed_kmh']]
y = df[['phri_score', 'projected_er_surge_pct']]

# Splitting the data into training and testing sets (80% training / 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training a RandomForestRegressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Model evaluation using MAE and R²
predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f" Mean Absolute Error (MAE): {mae:.2f}")
print(f"R² Score: {r2:.4f}")

joblib.dump(model, "phri_model.pkl")
print("Form saved as: phri_model.pkl")